In [7]:
import pandas as pd

In [3]:
data = {'name' : ['Nithin' , 'Chandu', 'Harsha', 'Rahul'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['nithin@gmail.com' , 'chandu@gmail.com' , 'harsha@gmail.com' , 'rahul@gmail.com'],
        'addr' : ['hyd', 'blr' , 'mum', 'pune']
    }

In [9]:
df = pd.DataFrame(data)

In [11]:
df

name  salary           mail_id  addr
0  Nithin     100  nithin@gmail.com   hyd
1  Chandu     200  chandu@gmail.com   blr
2  Harsha     300  harsha@gmail.com   mum
3   Rahul     400   rahul@gmail.com  pune

In [ ]:
name, location, role

In [11]:
data1 = {
    'name' : ['musthafa', 'sanjay', 'puran'],
    'location' : ['hyd', 'bglr', 'pune'],
    'role' : ['datascientist', 'ML Engineer', "python developer"]
}

In [13]:
data1 = {
    'name' : ['rohit', 'virat', 'hardik'],
    'location':['mumbai', 'delhi', 'bangalore'],
    'role' : ['data analyst', 'java developer', 'data scientist']
    
}

In [15]:
df1 = pd.DataFrame(data1)

In [17]:
df1

name   location            role
0   rohit     mumbai    data analyst
1   virat      delhi  java developer
2  hardik  bangalore  data scientist

In [21]:
df.head()

name  salary           mail_id  addr
0  Nithin     100  nithin@gmail.com   hyd
1  Chandu     200  chandu@gmail.com   blr
2  Harsha     300  harsha@gmail.com   mum
3   Rahul     400   rahul@gmail.com  pune

In [19]:
df.loc[1:3]

name  salary           mail_id  addr
1  Chandu     200  chandu@gmail.com   blr
2  Harsha     300  harsha@gmail.com   mum
3   Rahul     400   rahul@gmail.com  pune

In [27]:
df.iloc[1:3]

name  salary           mail_id addr
1  Chandu     200  chandu@gmail.com  blr
2  Harsha     300  harsha@gmail.com  mum

In [29]:
df.loc[10:15]

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [31]:
df.loc[10:15]

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [23]:
df.iloc[5:10]

name  salary             mail_id           addr
5     kavya     600     kavya@gmail.com  andhrapradesh
6    sriram     700    sriram@gmail.com          delhi
7    sanjay     800    sanjay@gmail.com        chennai
8  tapinder     900  tapinder@gmail.com     maharastra

In [33]:
data1 = {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
}

In [35]:
df1 = pd.DataFrame(data1)

In [37]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [39]:
df

name  salary           mail_id  addr
0  Nithin     100  nithin@gmail.com   hyd
1  Chandu     200  chandu@gmail.com   blr
2  Harsha     300  harsha@gmail.com   mum
3   Rahul     400   rahul@gmail.com  pune

In [41]:
pd.concat([df,df1])

name  salary           mail_id  addr    pf_nu  income_tax  mobile_no  \
0  Nithin   100.0  nithin@gmail.com   hyd      NaN         NaN        NaN   
1  Chandu   200.0  chandu@gmail.com   blr      NaN         NaN        NaN   
2  Harsha   300.0  harsha@gmail.com   mum      NaN         NaN        NaN   
3   Rahul   400.0   rahul@gmail.com  pune      NaN         NaN        NaN   
0     NaN     NaN               NaN   NaN    234.0       234.0    23543.0   
1     NaN     NaN               NaN   NaN     45.0       565.0    43543.0   
2     NaN     NaN               NaN   NaN  54465.0       767.0      454.0   
3     NaN     NaN               NaN   NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [43]:
pd.concat([df,df1] , axis=1)

name  salary           mail_id  addr  pf_nu  income_tax  mobile_no  \
0  Nithin     100  nithin@gmail.com   hyd    234         234      23543   
1  Chandu     200  chandu@gmail.com   blr     45         565      43543   
2  Harsha     300  harsha@gmail.com   mum  54465         767        454   
3   Rahul     400   rahul@gmail.com  pune    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [47]:
data2 = {'0' : ['Nithin' , 'Chandu' , 'Harsha'],
        '1' : [100 , 200 , 300 ],
        '2' : ['nithin@gmail.com' , 'chandu@gmail.com' , 'harsha@gmail.com'],
        '3' : ['hyd' , 'blr' , 'pune']
    }

In [49]:
df2 = pd.DataFrame(data2)

In [51]:
data3 = {'0' : [234, 45, 5446],
        '1' : [234, 565, 767],
        '2' : [23543, 43543, 454],
        '3' : ['ds' , 'bigdata' , 'web dev']
}

In [53]:
df3 = pd.DataFrame(data3)

In [55]:
df2

0    1                 2     3
0  Nithin  100  nithin@gmail.com   hyd
1  Chandu  200  chandu@gmail.com   blr
2  Harsha  300  harsha@gmail.com  pune

In [57]:
df3

0    1      2        3
0   234  234  23543       ds
1    45  565  43543  bigdata
2  5446  767    454  web dev

In [59]:
pd.concat([df2,df3])

0    1                 2        3
0  Nithin  100  nithin@gmail.com      hyd
1  Chandu  200  chandu@gmail.com      blr
2  Harsha  300  harsha@gmail.com     pune
0     234  234             23543       ds
1      45  565             43543  bigdata
2    5446  767               454  web dev

In [61]:
pd.concat([df2,df3], axis=1)

0    1                 2     3     0    1      2        3
0  Nithin  100  nithin@gmail.com   hyd   234  234  23543       ds
1  Chandu  200  chandu@gmail.com   blr    45  565  43543  bigdata
2  Harsha  300  harsha@gmail.com  pune  5446  767    454  web dev

In [63]:
data4 = {'emp_id' : [101,102,103],
         'salary' : [234, 345,200],
         'pf' : [23,34,56]
         }

In [65]:
data5  = {'emp_id' : [101, 102, 104],
          'mob_no' : [3434, 5656, 767],
          'house_nu' : [345, 345, 345]
}

In [67]:
df4 = pd.DataFrame(data4)

In [69]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56

In [73]:
df5 = pd.DataFrame(data5)

In [75]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345

In [77]:
pd.merge(df4,df5,  how ='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN

In [79]:
pd.merge(df5, df4, how = 'left')

emp_id  mob_no  house_nu  salary    pf
0     101    3434       345   234.0  23.0
1     102    5656       345   345.0  34.0
2     104     767       345     NaN   NaN

In [101]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56

In [103]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345

In [107]:
pd.merge(df4, df5, how = 'left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN

In [81]:
pd.merge(df4,df5 ,  how ='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104     NaN   NaN     767       345

In [83]:
pd.merge(df4, df5, how = 'right', on = 'emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104     NaN   NaN     767       345

In [85]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
}

In [87]:
df6 = pd.DataFrame(data6)

In [89]:
df7= pd.DataFrame(data7)

In [91]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [93]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [127]:
pd.merge(df6,df7, left_on = 'emp_id1' , right_on = 'emp_id2',how = 'inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [129]:
pd.merge(df7,df6, left_on='emp_id2', right_on='emp_id1', how = 'inner')

emp_id2  mob_no  house_nu  emp_id1  salary  pf
0      101    3434       345      101     234  23
1      102    5656       345      102     345  34
2      104     767       345      104     400  78

In [95]:
data8 = {'emp_id' : [101, 102, 103, 104],
         'salary' : [234, 345, 200, 400],
         'pf' : [23, 34, 56, 78],
         }

data9  = {'emp_id' : [101, 102, 104, 105, 123],
          'salary' : [234, 345, 200, 878, 43],
          'house_nu' : [345, 345, 345, 56, 234]
}

In [97]:
df8 = pd.DataFrame(data8)

In [99]:
df9 = pd.DataFrame(data9)

In [101]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [103]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56
4     123      43       234

In [105]:
pd.merge(df8,df9 , on = ['emp_id' , 'salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [119]:
data10 = {'emp_id1' : [101, 102, 103, 104],
         'salary1' : [234, 345, 200, 400],
         'pf' : [23, 34, 56, 78],
         }
data11  = {'emp_id2' : [101, 102, 104, 105, 123],
          'salary2' : [234, 345, 200, 878, 43],
          'house_nu' : [345, 345, 345, 56, 234]
}

In [121]:
df10 = pd.DataFrame(data10,index=['a' ,'b','c' ,'d'])

In [123]:
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [125]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [127]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [129]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [131]:
df11.join(df10)

emp_id2  salary2  house_nu  emp_id1  salary1    pf
a      101      234       345    101.0    234.0  23.0
b      102      345       345    102.0    345.0  34.0
d      104      200       345    104.0    400.0  78.0
e      105      878        56      NaN      NaN   NaN
f      123       43       234      NaN      NaN   NaN

In [133]:
df_sales  = pd.read_csv("sales_data_final.csv")

In [134]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [137]:
df_sales.shape

(51290, 21)

In [143]:
df_sales.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [145]:
df_sales.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [147]:
df_sales.describe()

quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [149]:
df_sales.describe().T

count         mean         std       min      25%      50%  \
quantity       51290.0     3.476545    2.278766     1.000     2.00     3.00   
discount       51290.0     0.142908    0.212280     0.000     0.00     0.00   
profit         51290.0    28.641740  174.424113 -6599.978     0.00     9.24   
shipping_cost  51290.0    26.375915   57.296804     0.000     2.61     7.79   
year           51290.0  2012.777208    1.098931  2011.000  2012.00  2013.00   

                   75%       max  
quantity          5.00    14.000  
discount          0.20     0.850  
profit           36.81  8399.976  
shipping_cost    24.45   933.570  
year           2014.00  2014.000

In [153]:
df_sales.duplicated().sum()

0

In [ ]:
def profit_flag(a) :
    if a >= 0 :
        return 'positive'
    else :
        return 'negative'

In [ ]:
profit_flag(-45)

'negative'

In [ ]:
profit_flag(45)

'positive'

In [ ]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [ ]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [246]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [248]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_quantity len_cust_name  
0          35.46          Medium  2011            low            15  
1           9.72          Medium  2011            low            11  
2           8.17            High  2011            low            13  
3           4.82            High  2011            low            12  
4           4.70          Medium  2011            low            11  

[5 rows x 23 columns]

In [232]:
def quantity_flag(a) :
    if  a < 10 :
        return 'low'
    elif a >10 and a <20 :
        return 'medium'
    else :
        return 'high'

In [242]:
df_sales['flag_quantity']= df_sales['quantity'].apply(quantity_flag)

In [244]:
df_sales.head(20)

order_id order_date ship_date       ship_mode      customer_name  \
0      AG-2011-2040   1/1/2011  1/6/2011  Standard Class    Toby Braunhardt   
1     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
2      HU-2011-1220   1/1/2011  1/5/2011    Second Class      Annie Thurman   
3   IT-2011-3647632   1/1/2011  1/5/2011    Second Class       Eugene Moren   
4     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
5     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
6      CA-2011-1510   1/2/2011  1/6/2011  Standard Class    Magdelene Morse   
7     IN-2011-79397   1/3/2011  1/3/2011        Same Day        Kean Nguyen   
8     ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
9      IZ-2011-4680   1/3/2011  1/7/2011  Standard Class   Lindsay Williams   
10    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
11    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
12  ES-2011-4869686   1/3/2011  1/7/2011  Standard Class  Dorothy Dickinson   
13    IN-2011-33652   1/3/2011  1/9/2011  Standard Class      Dennis Pardue   
14    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
15   MX-2011-160234   1/3/2011  1/7/2011  Standard Class   Stewart Visinsky   
16      IR-2011-770   1/3/2011  1/7/2011  Standard Class      Jas O'Carroll   
17    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
18    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
19    ID-2011-12596   1/3/2011  1/8/2011  Standard Class       Chris McAfee   

        segment              state         country  market          region  \
0      Consumer        Constantine         Algeria  Africa          Africa   
1      Consumer    New South Wales       Australia    APAC         Oceania   
2      Consumer           Budapest         Hungary    EMEA            EMEA   
3   Home Office          Stockholm          Sweden      EU           North   
4      Consumer    New South Wales       Australia    APAC         Oceania   
5      Consumer    New South Wales       Australia    APAC         Oceania   
6      Consumer            Ontario          Canada  Canada          Canada   
7     Corporate    New South Wales       Australia    APAC         Oceania   
8      Consumer           Auckland     New Zealand    APAC         Oceania   
9     Corporate             Ninawa            Iraq    EMEA            EMEA   
10     Consumer   National Capital     Philippines    APAC  Southeast Asia   
11     Consumer   National Capital     Philippines    APAC  Southeast Asia   
12     Consumer            England  United Kingdom      EU           North   
13  Home Office            Sarawak        Malaysia    APAC  Southeast Asia   
14     Consumer           Auckland     New Zealand    APAC         Oceania   
15     Consumer          Guatemala       Guatemala   LATAM         Central   
16     Consumer               Yazd            Iran    EMEA            EMEA   
17     Consumer           Auckland     New Zealand    APAC         Oceania   
18     Consumer           Auckland     New Zealand    APAC         Oceania   
19     Consumer  Nakhon Ratchasima        Thailand    APAC  Southeast Asia   

    ... sub_category                               product_name sales  \
0   ...      Storage                        Tenex Lockers, Blue   408   
1   ...     Supplies                   Acme Trimmer, High Speed   120   
2   ...      Storage                    Tenex Box, Single Width    66   
3   ...        Paper                Enermax Note Cards, Premium    45   
4   ...  Furnishings                 Eldon Light Bulb, Duo Pack   114   
5   ...        Paper    Eaton Computer Printout Paper, 8.5 x 11    55   
6   ...     Machines                   Okidata Inkjet, Wireless   314   
7   ...   Appliances                    Hoover Microwave, White   276   
8   ...      Copiers                Hewlett Wireless Fa

In [250]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_quantity len_cust_name  
0          35.46          Medium  2011            low            15  
1           9.72          Medium  2011            low            11  
2           8.17            High  2011            low            13  
3           4.82            High  2011            low            12  
4           4.70          Medium  2011            low            11  

[5 rows x 23 columns]

In [252]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)

In [254]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  \
0        2      0.0  106.140         35.46          Medium  2011   
1        3      0.1   36.036          9.72          Medium  2011   
2        4      0.0   29.640          8.17            High  2011   
3        3      0.5  -26.055          4.82            High  2011   
4        5      0.1   37.770          4.70          Medium  2011   

   flag_quantity  len_cust_name square_quantity  
0            low             15               4  
1            low             11               9  
2            low             13              16  
3            low             12               9  
4            low             11              25  

[5 rows x 24 columns]

In [256]:
import numpy as np

In [258]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [ ]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [ ]:
np.array([[2,3,4] , [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [ ]:
np.array([[1,2,3,4] , [ 2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
l = [[1,2,3,4] , [ 2,3,4,5]]

In [ ]:
l[0][0]

1

In [ ]:
a = np.array([3,4,5,6] , ndmin= 3)

In [ ]:
a

array([[[3, 4, 5, 6]]])

In [ ]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim

2

In [ ]:
np.random.randint(1,10,(4,4))

array([[9, 8, 5, 6],
       [2, 7, 3, 3],
       [9, 3, 2, 3],
       [3, 3, 1, 1]])

In [ ]:
np.random.randint(1,10,(4,4,2))

array([[[5, 2],
        [3, 3],
        [9, 4],
        [6, 4]],

       [[6, 6],
        [9, 4],
        [7, 2],
        [4, 2]],

       [[3, 3],
        [6, 9],
        [2, 8],
        [3, 3]],

       [[4, 4],
        [1, 3],
        [4, 6],
        [3, 6]]])

In [ ]:
#Task 1 - Fitbit Dataset

1. Read this dataset in pandas 
3. convert all the dates avaible in dataset to timestamp format in pandas
4 . Find out in this data that how many unique id's we have
5 . which id is one of the active id that you have in whole dataset
6 . how many of them have not logged there activity find out in terms of number of ids
7 . Find out who is the laziest person id that we have in dataset
8 . Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset
9. how many person are not a regular person with respect to activity try to find out those
10 . who is the thired most active person in this dataset find out those in pandas.
11 . who is the 5th most laziest person avilable in dataset find it out
12 . what is a totla acumulative calories burn for a person find out


In [ ]:
#task 2 - Superstore_USA
1 . load this data in pandas 
2 . Find out how return that we ahve recived and with a product id
4 . try  to join order and return data pandas
5 . Try to find out how many unique customer that we have
6 . try to find out in how many regions we are selling a product and who is a manager for a respective region
7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset
8 . Create a new coulmn and try to find our a diffrence between order date and shipment date
9 . base on question number 8 find out for which order id we have shipment duration more than 10 days
10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well
11 . Gorup by region and find out which region is more profitable
12 . Try to find out overalll in which country we are giving more didscount
13 . Give me a list of unique postal code
14 . which customer segement is more profitalble find it out .
15 . try to find out the 10th most loss making product catagory .
16 . Try to find out 10 top  product with highest margins

SyntaxError: invalid syntax (2613182746.py, line 2)